# Generated by Django 5.0.4 on 2024-04-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-id"]},
        ),
    ]
